name: flutter_final_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.5.0 # Replace with the latest version

  flutter_dotenv: ^5.2.1 # Use the latest version



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  

flutter:
  uses-material-design: true


  assets:
  - .env
